apiVersion: v1
kind: Service
metadata:
  name: payment-devpay
  namespace: aex
  labels:
    app.kubernetes.io/name: payment-devpay
    app.kubernetes.io/component: payment-agent
    app.kubernetes.io/part-of: agent-exchange
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-devpay
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: http
